// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinances.Infrastructure.Database;

#nullable disable

namespace MyFinances.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.AllocationDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("allocations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bank"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Investment"
                        });
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.CategoryDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("ReferenceCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Categories_ReferenceCode");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Categories_UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Categories_UserId_Name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.ExpenseTypeDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("expense_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Appelant"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sporadic"
                        });
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.InstallmentDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllocationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateForPayment")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsPayed")
                        .HasColumnType("bit");

                    b.Property<int>("PlannedExpenseId")
                        .HasColumnType("int");

                    b.Property<Guid>("ReferenceCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("RequiredAmount")
                        .HasColumnType("int");

                    b.Property<int>("ReservedAmount")
                        .HasColumnType("int");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.HasIndex("DateForPayment")
                        .HasDatabaseName("IX_Installments_DateForPayment");

                    b.HasIndex("PlannedExpenseId")
                        .HasDatabaseName("IX_Installments_PlannedExpenseId");

                    b.HasIndex("ReferenceCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Installments_ReferenceCode");

                    b.ToTable("installments", (string)null);
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.PlannedExpenseDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expense_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ReferenceCode")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true)
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("WalletCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Planned_Expenses_Date");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Planned_Expenses_Name");

                    b.HasIndex("ReferenceCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Planned_Expenses_ReferenceCode");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("IX_Planned_Expenses_TypeId");

                    b.HasIndex("WalletCategoryId")
                        .HasDatabaseName("IX_Planned_Expenses_WalletCategoryId");

                    b.ToTable("planned_expenses", (string)null);
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.TransactionsTypeDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("transactions_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Icome"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Expense"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Transfer"
                        });
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.UserDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.WalletCategoryDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double>("Percent")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Wallets_Categories_Join_CategoryId");

                    b.HasIndex("WalletId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("UX_Wallets_Categories_Join_WalletId_CategoryId")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("wallets_categories_join", (string)null);
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.WalletCategoryTransactionDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllocationId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ReferenceCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("WalletCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId")
                        .HasDatabaseName("IX_Transactions_AllocationId");

                    b.HasIndex("Amount")
                        .HasDatabaseName("IX_Transactions_Amount");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Transactions_Date");

                    b.HasIndex("ReferenceCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Transactions_ReferenceCode");

                    b.HasIndex("TransactionTypeId")
                        .HasDatabaseName("IX_Transactions_TypeId");

                    b.HasIndex("WalletCategoryId")
                        .HasDatabaseName("IX_Transactions_WalletCategoryId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.WalletDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("ReferenceCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Wallet_ReferenceCode");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Wallet_UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Wallet_UserId_Name");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.CategoryDbModel", b =>
                {
                    b.HasOne("MyFinances.Application.Common.Database.DbModels.UserDbModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.InstallmentDbModel", b =>
                {
                    b.HasOne("MyFinances.Application.Common.Database.DbModels.AllocationDbModel", "Allocation")
                        .WithMany("Installments")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MyFinances.Application.Common.Database.DbModels.PlannedExpenseDbModel", "PlannedExpense")
                        .WithMany("Installments")
                        .HasForeignKey("PlannedExpenseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Allocation");

                    b.Navigation("PlannedExpense");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.PlannedExpenseDbModel", b =>
                {
                    b.HasOne("MyFinances.Application.Common.Database.DbModels.ExpenseTypeDbModel", "Type")
                        .WithMany("PlannedExpenses")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MyFinances.Application.Common.Database.DbModels.WalletCategoryDbModel", "WalletCategory")
                        .WithMany("PlannedExpenses")
                        .HasForeignKey("WalletCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Type");

                    b.Navigation("WalletCategory");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.WalletCategoryDbModel", b =>
                {
                    b.HasOne("MyFinances.Application.Common.Database.DbModels.CategoryDbModel", "Category")
                        .WithMany("CategoryWallets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MyFinances.Application.Common.Database.DbModels.WalletDbModel", "Wallet")
                        .WithMany("WalletCategories")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.WalletCategoryTransactionDbModel", b =>
                {
                    b.HasOne("MyFinances.Application.Common.Database.DbModels.AllocationDbModel", "Allocation")
                        .WithMany("Transactions")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MyFinances.Application.Common.Database.DbModels.TransactionsTypeDbModel", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MyFinances.Application.Common.Database.DbModels.WalletCategoryDbModel", "WalletCategory")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Allocation");

                    b.Navigation("TransactionType");

                    b.Navigation("WalletCategory");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.WalletDbModel", b =>
                {
                    b.HasOne("MyFinances.Application.Common.Database.DbModels.UserDbModel", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.AllocationDbModel", b =>
                {
                    b.Navigation("Installments");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.CategoryDbModel", b =>
                {
                    b.Navigation("CategoryWallets");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.ExpenseTypeDbModel", b =>
                {
                    b.Navigation("PlannedExpenses");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.PlannedExpenseDbModel", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.TransactionsTypeDbModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.UserDbModel", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.WalletCategoryDbModel", b =>
                {
                    b.Navigation("PlannedExpenses");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyFinances.Application.Common.Database.DbModels.WalletDbModel", b =>
                {
                    b.Navigation("WalletCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
